In [1]:
import torch
from torch import nn, optim
from jcopdl.callback import Callback, set_config

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

In [2]:
import torch.nn as nn
import torchvision

# Creating Basic Tensors

A number, vector, matrix or any n-dimensional array is represented in Tensor form in Pytorch framework library.

a) number

In [4]:
v1 = torch.tensor((4., 3.))
v1

tensor([4., 3.])

In [5]:
v1.shape

torch.Size([2])

In [7]:
v1.dtype

torch.float32

b) vector

In [8]:
v2 = torch.tensor([11., 33, 55, 77, 99])
v2

tensor([11., 33., 55., 77., 99.])

In [9]:
v2.shape

torch.Size([5])

In [10]:
v2.dtype

torch.float32

c) matrix

In [11]:
v3 = torch.tensor([[149, 218, 105,  177],
                  [18,  161, 220,  54],
                  [144, 195, 180,  63],
                  [208, 162, 207,  25]])

In [12]:
v3.shape

torch.Size([4, 4])

In [13]:
v3.dtype

torch.int64

d) 3 dimensional array

In [14]:
v4 = torch.tensor(([[[71, 94, 4, 871],
                     [13, 67, 410, 8],
                     [283, 74, 31, 90]],
                    [[46, 124,  134, 101],
                     [187, 224, 197, 771],
                     [409, 51, 889, 100]],
                    [[85, 89, 341, 88],
                     [101, 6, 33, 111],
                     [391, 709, 2, 92]]]))

In [17]:
v4

tensor([[[ 71,  94,   4, 871],
         [ 13,  67, 410,   8],
         [283,  74,  31,  90]],

        [[ 46, 124, 134, 101],
         [187, 224, 197, 771],
         [409,  51, 889, 100]],

        [[ 85,  89, 341,  88],
         [101,   6,  33, 111],
         [391, 709,   2,  92]]])

In [15]:
v4.shape

torch.Size([3, 3, 4])

In [16]:
v4.dtype

torch.int64

# Reshape

In [23]:
v5 = v4.view(4, -1)
v5

tensor([[ 71,  94,   4, 871,  13,  67, 410,   8, 283],
        [ 74,  31,  90,  46, 124, 134, 101, 187, 224],
        [197, 771, 409,  51, 889, 100,  85,  89, 341],
        [ 88, 101,   6,  33, 111, 391, 709,   2,  92]])

In [34]:
v5.shape

torch.Size([4, 9])

In [25]:
v6 = v4.view(1, 3, 3, 4)
v6

tensor([[[[ 71,  94,   4, 871],
          [ 13,  67, 410,   8],
          [283,  74,  31,  90]],

         [[ 46, 124, 134, 101],
          [187, 224, 197, 771],
          [409,  51, 889, 100]],

         [[ 85,  89, 341,  88],
          [101,   6,  33, 111],
          [391, 709,   2,  92]]]])

In [35]:
v6.shape

torch.Size([1, 3, 3, 4])

# Permute

In [39]:
v6.permute(1, 0, 2, 3)

tensor([[[[ 71,  94,   4, 871],
          [ 13,  67, 410,   8],
          [283,  74,  31,  90]]],


        [[[ 46, 124, 134, 101],
          [187, 224, 197, 771],
          [409,  51, 889, 100]]],


        [[[ 85,  89, 341,  88],
          [101,   6,  33, 111],
          [391, 709,   2,  92]]]])

In [40]:
v6.permute(1, 0, 2, 3).shape

torch.Size([3, 1, 3, 4])

# Convert Tensor to Numpy array

In [28]:
v7 = v4.numpy()
v7

array([[[ 71,  94,   4, 871],
        [ 13,  67, 410,   8],
        [283,  74,  31,  90]],

       [[ 46, 124, 134, 101],
        [187, 224, 197, 771],
        [409,  51, 889, 100]],

       [[ 85,  89, 341,  88],
        [101,   6,  33, 111],
        [391, 709,   2,  92]]], dtype=int64)

# Tensor Operation and Gradient

In [49]:
x = torch.tensor([[5., 12., 8.,  3.],
                  [4.,  17., 16.,  22.]
                 ])
w = torch.tensor([[2.3, 1.6, 1.9, .4],
                  [2.9, 3.5, 5.1, 3.3]], requires_grad=True)
b = torch.tensor([[2., 5., 3., 6.],
                  [4., 7., 8., 0.]], requires_grad=True)

y = x**2 - w * x + b
y

tensor([[ 15.5000, 129.8000,  51.8000,  13.8000],
        [  8.4000, 236.5000, 182.4000, 411.4000]], grad_fn=<AddBackward0>)

In [50]:
out = y.mean()
out

tensor(131.2000, grad_fn=<MeanBackward0>)

PyTorch features the backward function to calculate the derivation value of polinomial equation. With b and w having requires_grad set to True,
gradient in tensor w and b would be the derivate of y stored in .grad property of w and b

In [51]:
# To compute the derivatives, call the .backward method on y

out.backward()

In [52]:
print(w.grad)
print(b.grad)

tensor([[-0.6250, -1.5000, -1.0000, -0.3750],
        [-0.5000, -2.1250, -2.0000, -2.7500]])
tensor([[0.1250, 0.1250, 0.1250, 0.1250],
        [0.1250, 0.1250, 0.1250, 0.1250]])
