<a href="https://colab.research.google.com/github/rizdiaprilian/Numpy_Stack_for_Deep_Learning/blob/main/Start_Your_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array vs List

In [5]:
import numpy as np

In [ ]:
U = [4, 21, 54, 90, 108]

In [ ]:
R = np.array([4, 21, 54, 90, 108])

In [ ]:
for h in U:
  print(h)

4
21
54
90
108


In [ ]:
for g in R:
  print(g)

4
21
54
90
108


In [ ]:
U.append(92)

In [ ]:
U

[4, 21, 54, 90, 108, 92]

In [ ]:
U + [97]

[4, 21, 54, 90, 108, 92, 97]

In [ ]:
R + np.array([3])

array([  7,  24,  57,  93, 111])

In [ ]:
R +  np.array([2,4,6,8,10])

array([  6,  25,  60,  98, 118])

In [ ]:
R +  np.array([2,4,6])

ValueError: ignored

In [ ]:
2 * R

array([  8,  42, 108, 180, 216])

In [ ]:
2 * U

[4, 21, 54, 90, 108, 92, 4, 21, 54, 90, 108, 92]

In [ ]:
U + U

[4, 21, 54, 90, 108, 92, 4, 21, 54, 90, 108, 92]

In [ ]:
U2 = []

for t in U:
  U2.append(t + 5)

In [ ]:
U2

[9, 26, 59, 95, 113, 97]

In [ ]:
U2 = [t + 5 for t in U]
U2

[9, 26, 59, 95, 113, 97]

In [ ]:
U ** 2

TypeError: ignored

In [ ]:
U3 = []

for t in U:
  U3.append(t ** 2)

U3

[16, 441, 2916, 8100, 11664, 8464]

In [ ]:
R ** 2

array([   16,   441,  2916,  8100, 11664])

In [ ]:
np.sqrt(R)

array([ 2.        ,  4.58257569,  7.34846923,  9.48683298, 10.39230485])

In [ ]:
np.log(R)

array([1.38629436, 3.04452244, 3.98898405, 4.49980967, 4.68213123])

In [ ]:
np.exp(R)

array([5.45981500e+01, 1.31881573e+09, 2.83075330e+23, 1.22040329e+39,
       8.01316426e+46])

# The Dot Product

In [ ]:
f = np.array([3, 4, 7])
g = np.array([2, 3, 1])

In [ ]:
dot = 0

for i, o in zip(f, g):
  dot += i * o

dot

25

In [ ]:
dot = 0

for i in range(len(f)):
  dot += f[i] * g[i]

dot

25

In [ ]:
f * g

array([ 6, 12,  7])

In [ ]:
np.sum(f * g)

25

In [ ]:
(f * g).sum()

25

In [ ]:
np.dot(f, g)

25

In [ ]:
f.dot(g)

25

In [ ]:
amag = np.sqrt((f * f).sum())
amag

8.602325267042627

In [ ]:
np.linalg.norm(f)

8.602325267042627

In [ ]:
cosangle = f.dot(g) / (np.linalg.norm(f) * np.linalg.norm(g))

In [ ]:
cosangle

0.7767122075015

In [ ]:
angle = np.arccos(cosangle)
angle

0.6813673571178105

# Speed Test

In [ ]:
## Speed comparison ##

## You can also use %timeit

from datetime import datetime

j = np.random.randn(100)
k = np.random.randn(100)

T = 100000

def slow_dot_product(a, b):
  result  = 0
  for i, j in zip(a, b):
    result += a * b
  return result

#### dot product 1 running ###
t0 = datetime.now()

for t in range(T):
  slow_dot_product(j, k)

dt1 = datetime.now() - t0

#### dot product 2 unning ###
t0_1 = datetime.now()

for t in range(T):
  j.dot(k)

dt2 = datetime.now() - t0_1

### Printing difference #####

print("dt_1 / dt_2:", dt1.total_seconds() / dt2.total_seconds())

dt_1 / dt_2: 221.39393205430554


# Matrices

In [56]:
%%timeit
O = [[2, 6], [3, 10]]
O

The slowest run took 13.09 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 109 ns per loop


In [2]:
O[0]

[2, 6]

In [3]:
O[0][1]

6

In [57]:
%%timeit
P = np.array([[2,6], [3,0]])
P

The slowest run took 17.53 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.54 µs per loop


In [7]:
P[0][1]

6

In [8]:
P[:,0]

array([2, 3])

In [9]:
P.T

array([[2, 3],
       [6, 0]])

In [10]:
np.exp(P)

array([[  7.3890561 , 403.42879349],
       [ 20.08553692,   1.        ]])

In [11]:
np.exp(O)

array([[7.38905610e+00, 4.03428793e+02],
       [2.00855369e+01, 2.20264658e+04]])

In [12]:
Q = np.array([[51, 49, 21],[79, 35, 90]])
Q

array([[51, 49, 21],
       [79, 35, 90]])

In [13]:
P.dot(Q)

array([[576, 308, 582],
       [153, 147,  63]])

In [15]:
np.linalg.det(P)

-17.999999999999996

In [16]:
np.linalg.inv(P)

array([[ 0.        ,  0.33333333],
       [ 0.16666667, -0.11111111]])

In [17]:
np.linalg.inv(P).dot(P)

array([[1., 0.],
       [0., 1.]])

In [18]:
np.trace(P)

2

In [19]:
np.diag(P)

array([2, 0])

In [20]:
np.linalg.eig(P)

(array([ 5.35889894, -3.35889894]), array([[ 0.87257427, -0.7458292 ],
        [ 0.48848147,  0.66613722]]))

In [21]:
K, m = np.linalg.eig(P)

In [22]:
m[:, 0] * K[0] == P @ m[:, 0]

array([False,  True])

In [23]:
m[:, 0] * K[0],P @ m[:, 0]

(array([4.67603734, 2.61772281]), array([4.67603734, 2.61772281]))

In [24]:
np.allclose(m[:, 0] * K[0], P @ m[:, 0])

True

In [25]:
np.allclose(m @ np.diag(K), P @ m)

True

# Linear Systems

In [ ]:
## Reminder 

x = np.linalg.inv(A).dot(B)   # No
x = np.linalg.solve(A, B)     # Yes

In [28]:
A = np.array([[1, 1],[1.5, 4]])
B = np.array([2200, 5050])

In [29]:
np.linalg.solve(A, B)

array([1500.,  700.])

In [30]:
np.linalg.inv(A).dot(B)

array([1500.,  700.])

# Generating Data

In [31]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
7 * np.ones((2, 3))

array([[7., 7., 7.],
       [7., 7., 7.]])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.random.random()

0.9036610240053489

In [37]:
np.random.random((2, 3))

array([[0.38024488, 0.07236989, 0.64845379],
       [0.35747034, 0.57790863, 0.69085397]])

In [38]:
np.random.randn(2, 3)

array([[ 2.90016918, -1.07932564,  0.14651846],
       [-0.75672545, -0.93700805, -0.93097025]])

In [39]:
T = np.random.randn(10000)
T.mean()

0.004318783573642795

In [40]:
np.mean(T)

0.004318783573642795

In [41]:
T.var()

1.0011097663970654

In [42]:
T.std()

1.0005547293362145

In [43]:
Y = np.random.randn(10000, 3)

In [44]:
Y.mean(axis=0)

array([ 0.00112936, -0.00130496,  0.00708143])

In [46]:
Y.mean(axis=1).shape

(10000,)

In [47]:
np.cov(Y)

array([[ 0.22818088,  0.09875274,  0.30051899, ...,  0.12052753,
         0.52952357,  0.28971409],
       [ 0.09875274,  0.37036285, -0.06462568, ..., -0.08354966,
        -0.14833768,  0.52282498],
       [ 0.30051899, -0.06462568,  0.51147806, ...,  0.23938173,
         0.92172023,  0.14538664],
       ...,
       [ 0.12052753, -0.08354966,  0.23938173, ...,  0.11987986,
         0.43607441, -0.01160233],
       [ 0.52952357, -0.14833768,  0.92172023, ...,  0.43607441,
         1.66381169,  0.2143658 ],
       [ 0.28971409,  0.52282498,  0.14538664, ..., -0.01160233,
         0.2143658 ,  0.84997818]])

In [48]:
np.cov(Y).shape

(10000, 10000)

In [50]:
np.cov(Y.T)

array([[ 1.01105045e+00,  9.85872917e-04, -8.45179785e-03],
       [ 9.85872917e-04,  9.92844686e-01, -2.81168062e-03],
       [-8.45179785e-03, -2.81168062e-03,  9.84218448e-01]])

In [52]:
np.cov(Y, rowvar=False)

array([[ 1.01105045e+00,  9.85872917e-04, -8.45179785e-03],
       [ 9.85872917e-04,  9.92844686e-01, -2.81168062e-03],
       [-8.45179785e-03, -2.81168062e-03,  9.84218448e-01]])

In [53]:
np.random.randint(0, 10, size=(3, 3))

array([[8, 0, 0],
       [6, 4, 4],
       [4, 9, 9]])

In [54]:
np.random.choice(10, size=(3, 3))

array([[6, 3, 5],
       [9, 0, 7],
       [2, 5, 9]])